````markdown id="helm-values-tgb-01"
# AWS Target Group Binding Configuration

This Helm values file contains the AWS Target Group ARN used by the Kubernetes TargetGroupBinding resource.

The ARN connects a Kubernetes Service to an existing AWS Application Load Balancer (ALB) Target Group using the AWS Load Balancer Controller.

This allows external traffic from the ALB to be routed directly to Kubernetes pods.

---

# Complete Configuration

```yaml
tgb:

  # AWS Target Group ARN
  arn: arn:aws:elasticloadbalancing:us-east-1:160885265516:targetgroup/roboshop-dev-frontend/a9ce21d069282d84
```

---

# What is a Target Group?

A Target Group is an AWS Application Load Balancer component that contains backend targets.

Targets can be:

```text
EC2 Instances
IP Addresses
Lambda Functions
Kubernetes Pods
```

Traffic Flow:

```text
User
  │
  ▼
Application Load Balancer
  │
  ▼
Target Group
  │
  ▼
Backend Targets
```

---

# What is TargetGroupBinding?

TargetGroupBinding is a Kubernetes Custom Resource created by the AWS Load Balancer Controller.

Purpose:

```text
Connect Existing AWS Target Group
to Kubernetes Service
```

Example:

```yaml
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
```

---

# Architecture Overview

```text
Internet User
      │
      ▼
AWS Application Load Balancer
      │
      ▼
Target Group
(roboshop-dev-frontend)
      │
      ▼
TargetGroupBinding
      │
      ▼
Frontend Service
      │
      ▼
Frontend Pods
```

---

# Understanding the ARN

```text
arn:aws:elasticloadbalancing:us-east-1:160885265516:targetgroup/roboshop-dev-frontend/a9ce21d069282d84
```

Breakdown:

```text
arn
 │
 ├── aws
 │
 ├── elasticloadbalancing
 │
 ├── us-east-1
 │
 ├── 160885265516
 │
 ├── targetgroup
 │
 ├── roboshop-dev-frontend
 │
 └── a9ce21d069282d84
```

---

# Region

```text
us-east-1
```

AWS region where the Target Group exists.

Example:

```text
N. Virginia
```

The EKS cluster and ALB should typically exist in the same region.

---

# AWS Account

```text
160885265516
```

AWS Account ID owning the Target Group.

Used for:

```text
Resource Identification
Cross-Service Integration
IAM Permissions
```

---

# Target Group Name

```text
roboshop-dev-frontend
```

Target Group created for:

```text
Roboshop Frontend
Development Environment
```

Naming Convention:

```text
<Project>-<Environment>-<Component>
```

Example:

```text
roboshop-dev-frontend
roboshop-qa-frontend
roboshop-prod-frontend
```

---

# Target Group ID

```text
a9ce21d069282d84
```

Unique identifier generated by AWS.

Used internally to distinguish Target Groups.

---

# How Helm Uses This Value

The value is injected into the TargetGroupBinding manifest.

Example:

```yaml
spec:

  targetGroupARN: {{ .Values.tgb.arn }}
```

Helm renders:

```yaml
spec:

  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:160885265516:targetgroup/roboshop-dev-frontend/a9ce21d069282d84
```

---

# Deployment Flow

```text
Helm Install
      │
      ▼
Read values.yaml
      │
      ▼
Read Target Group ARN
      │
      ▼
Create TargetGroupBinding
      │
      ▼
AWS Load Balancer Controller
      │
      ▼
Register Frontend Pods
      │
      ▼
Traffic Starts Flowing
```

---

# Request Flow

```text
User
  │
  ▼
AWS ALB
  │
  ▼
Target Group
  │
  ▼
Frontend Pod IPs
  │
  ▼
Frontend Service
  │
  ▼
Frontend Container
```

---

# Example Environment-Specific Values

## Development

```yaml
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/roboshop-dev-frontend/abc123
```

---

## QA

```yaml
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/roboshop-qa-frontend/def456
```

---

## Production

```yaml
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/roboshop-prod-frontend/xyz789
```

---

# Benefits of Using Values File

Instead of hardcoding:

```yaml
targetGroupARN:
  arn:aws:elasticloadbalancing:...
```

inside manifests, Helm values provide:

✅ Environment Separation

✅ Reusable Templates

✅ Easier Maintenance

✅ GitOps Friendly Deployments

✅ Reduced Configuration Duplication

---

# Real DevOps Use Cases

## Amazon EKS

Expose Kubernetes applications using ALB.

---

## Multi-Environment Deployments

Separate:

```text
DEV
QA
UAT
PROD
```

Target Groups.

---

## GitOps

Tools like:

- :contentReference[oaicite:0]{index=0}

deploy different values files per environment.

---

## Blue-Green Deployments

Traffic can be switched between Target Groups.

---

# Best Practices

✅ Store Target Group ARN in values.yaml

✅ Use separate values files per environment

✅ Use descriptive Target Group names

✅ Keep ALB and EKS in the same region

✅ Register pod IPs directly (`targetType: ip`)

---

# Why This Configuration Is Important

This value connects Kubernetes workloads with AWS networking infrastructure.

Without this ARN:

```text
ALB
  │
  ▼
Target Group
  ✖
Kubernetes Service
```

cannot communicate.

Understanding Target Group ARNs and TargetGroupBinding is important for:

- DevOps Engineers
- Platform Engineers
- Kubernetes Administrators
- Cloud Engineers
- Amazon EKS Operations
````
